# Dockerfile.frontend
FROM nginx:stable-alpine
LABEL maintainer="dhanush"

# custom nginx config (we'll add nginx.conf next)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# copy static website
COPY website/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]